"""empty message

Revision ID: 595d6dee77f6
Revises: d6ca85391b70
Create Date: 2025-10-16 01:26:37.338001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '595d6dee77f6'
down_revision: Union[str, None] = 'd6ca85391b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('admin', 'user', name='role'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
